### ISSUE TITLE
Window size doesn't get recorded if the app is quit

### ISSUE THREAD

**Issue by kra-mo** [vixalien/decibels#15]
It only gets recorded if the window is closed, because saving the schema is currently tied to the `close-request` signal. If the app is quit via Ctrl+Q or by force quitting, it does not.

**Comment by vixalien** [comment]
thanks for this

**Comment by vixalien** [comment]
I'm not sure how to fix this, because apps like amberol also save the window state on close-request.

**Comment by kra-mo** [comment]
It's easiest to bind three schemas to the `"default-width"`, `"default-height"` and `"maximized"` properties of the window. It's also how the [docs](https://developer.gnome.org/documentation/tutorials/save-state.html) suggest you do it.

**Comment by vixalien** [comment]
thanks
