### ISSUE TITLE
Can't set as default audio file handler

### ISSUE THREAD

**Issue by aadilayub** [vixalien/decibels#24]
I want to set Decibels as the default app for playing audio files, but I can't find it in the "open with" menu:

![image](https://github.com/vixalien/decibels/assets/31581044/18c71512-feda-41e2-bd58-d298796d4f36)

**Comment by vixalien** [comment]
Can you try setting it as the default app in Settings > Default Apps > Music.

On the screenshot you sent me, maybe Decibels is the first app on the list?

**Comment by aadilayub** [comment]
Setting it as default in the settings menu worked!

**Comment by aadilayub** [comment]
> Can you try setting it as the default app in Settings > Default Apps > Music.
> 
> On the screenshot you sent me, maybe Decibels is the first app on the list?

It shows up in the list after setting it as default through the settings menu. Previously it wasn't there

**Comment by vixalien** [comment]
Hello. Please try installing the [latest flatpak artefact](https://github.com/vixalien/decibels/suites/17379253308/artifacts/993212971) and confirm it fixes the issue.

Let me know if the issue is indeed fixed so I can push out a new release with the fixes ASAP.

**Comment by aadilayub** [comment]
It works now!

![image](https://github.com/vixalien/decibels/assets/31581044/44a8b606-12e2-4275-9280-4d427709858b)
