### ISSUE TITLE
Feature request: Shortcuts for seek forward/backward

### ISSUE THREAD

**Issue by prometoys** [vixalien/decibels#28]
Hi,

first: I really like your app and for me as a tech journalist it is very helpful to listen to interview recordings and transcribe it. 

I would like to use the backward/forward  keys (⏪/⏩)  on my keyboard to seek back/forward in Decibel. So I can stay in my text editor, but rewind a few seconds, when I missed a word or sentence. 

It would be nice, if by default Decibel would register to the key events (AudioNext?, AudioPrev?), like it reacts when I push the Play-Key on my keyboard (AudioPlay?).

Because Decibel don't support multiple tracks (which is fine for me), I think it is okay, if AudioNext/AudioPrev is bend to seek fwd/bwd. 

Offtopic: I have more Ideas. Should I open more issues here on GitHub?

**Comment by vixalien** [comment]
> I think it is okay, if AudioNext/AudioPrev is bend to seek fwd/bwd.

I can implement this, but I'm not sure if it's desirable from a design perspective.

> Offtopic: I have more Ideas. Should I open more issues here on GitHub?

Yes, please!!
