### ISSUE TITLE
Feature request: Add blurred image in background if audio file has a cover

### ISSUE THREAD

**Issue by stardustspirit** [vixalien/decibels#43]
I think it would be nice if Decibels took the song art (if it exists) and used it in the background for some more color, similar to the effect used in Ticket Booth:
![image](https://github.com/vixalien/decibels/assets/56515875/40e09685-a3de-4532-90a3-3919f474af24)

**Comment by vixalien** [comment]
This would indeed look nice, thanks for the feature request

**Comment by stardustspirit** [comment]
That would probably make more sense
