### ISSUE TITLE
Audio speed field not cleared when starting new song

### ISSUE THREAD

**Issue by BlobCodes** [vixalien/decibels#44]
When opening a new song with decibels while another song is playing, the currently playing song gets replaced (not sure if that's a good thing, but that's not what this issue is about).

If the previously playing audio file was played at a different speed, the input field showing this value does not get reset, even though the new song is clearly playing at normal (x1.0) speed.

Here's a video demonstrating the issue:

[Bildschirmaufzeichnung vom 2023-12-16, 02-13-18.webm](https://github.com/vixalien/decibels/assets/14961554/5265fffb-af10-4dcb-8a69-69efef0dd2e9)

**Comment by vixalien** [comment]
Thanks for reporting this!

**Comment by vixalien** [comment]
This issue can be solved by notifying the player that the playback rate changed after the `uri-loaded` signal.

The handler is here:

https://github.com/vixalien/decibels/blob/686f2bc3999109eccb2520f4876a4b6a78bc3dcb/src/stream.ts#L529-L532

What needs to be done is add a `this.notify("rate")` here. PRs are welcome!
