### ISSUE TITLE
Selection support of multiple audio files

### ISSUE THREAD

**Issue by Ricky-Tigg** [vixalien/decibels#56]
**v.:** 0.1.7. Hello. First attempt, with a _flac_-typed audio file – success. As intended selection of at most one audio file is supported. Would you agree to bring support for selection of **multiple audio files** either as such or via the selection of a folder? In the eventuality of a positive answer, as a result, sound track titles would be then visible as part of a play-list.

Related support suggestions:
- Multiple removals of items at once from the play-list. Audio files associated to removals would not be deleted.
- Saving multiple play-lists; ideally by name.

**Comment by vixalien** [comment]
Hmm, sorry, but Decibels is explicitly designed for playing single files. If you want a playlist (and a queue), you can use alternative apps like [GNOME Music](apps.gnome.org/Music) or [Amberol](https://apps.gnome.org/Amberol/).

Quoting https://gitlab.gnome.org/bertob/app-ideas/-/issues/216:

> A standalone app for playing individual audio files (and maybe short playlists, but the focus is on single files). Something like Amberol but less focused on music and more on things like audio recordings, podcasts, and the like.
Some
