### ISSUE TITLE
Scrolling on progress bar doesn't do anything

### ISSUE THREAD

**Issue by kra-mo** [vixalien/decibels#7]
Currently, scrolling on it only makes the audio lag.

(I'm not sure whether allowing it to be scrolled in the first place is intentional or not, but if it is, the waveform should probably be scrollable too.)

**Comment by vixalien** [comment]
hmm. Im not sure about this. seems like it's just how GtkScale's works. I'm not sure if it should be scrollable?

**Comment by vixalien** [comment]
were you talking about scrolling on the progress bar or the waveform?

**Comment by kra-mo** [comment]
Scrolling on the progress bar. This is definitely unexpected.
